name: Deploy happy stack

on:
  workflow_run:
    workflows: [🏗️ Build]
    types: [completed]
    branches: [main]

jobs:
  create-update-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: deploy rdev-stable and staging
    concurrency: staging_environment
    runs-on: ubuntu-latest
    steps:
      - name: Push staging
        run: exit 1

  create-update-prod:
    needs: [create-update-staging]
    concurrency:
      group: prod_environment
      cancel-in-progress: true
    environment: prod # NOTE if env isn't defined than we got problems
    runs-on: ubuntu-latest
    name: deploy production
    steps:
      - name: Push to prod
        run: echo "pushing to prod"
