name: Push to prod

concurrency: prod_environment

on:
  workflow_run:
    workflows: [Push to staging]
    types: [completed]
    branches: [main]


jobs:
  create-update-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: prod
    name: Push Prod
    runs-on: ubuntu-latest
    steps:
      - name: Push to prod
        run: echo "pushing to prod"

# what if the env isn't defined